// ── Notification routes: user alerts and messages ──
// Authenticated users can view their notifications and mark them as read
// Notifications cover insurance expiry, license renewal, PUC alerts, etc.
// In production these would be generated by scheduled jobs / DB triggers

import { Router, Response } from 'express';
import { authenticate, AuthRequest } from '../middleware/auth';

const router = Router();

// In-memory notification store with realistic sample data for development
const notifications: Array<{
  id: string; userId: string; title: string; message: string;
  type: string; isRead: boolean; createdAt: string;
}> = [
  {
    id: '1', userId: '0', title: 'Insurance Expiring Soon',
    message: 'Your vehicle PY-01-AB-1234 insurance expires in 15 days.',
    type: 'WARNING', isRead: false, createdAt: '2026-07-01',
  },
  {
    id: '2', userId: '0', title: 'License Renewal Due',
    message: 'Your driving license expires on 2026-09-15. Please renew.',
    type: 'INFO', isRead: false, createdAt: '2026-06-28',
  },
  {
    id: '3', userId: '0', title: 'PUC Expired',
    message: 'Your PUC certificate has expired. Get a fresh PUC test.',
    type: 'ALERT', isRead: true, createdAt: '2026-06-15',
  },
];

// ── GET /api/notifications ──
// Returns notifications for the authenticated user (currently shows all as demo)
router.get('/', authenticate, (req: AuthRequest, res: Response) => {
  const userNotifs = notifications.filter((n) => n.userId === req.user!.userId || true);
  res.json({ notifications: userNotifs });
});

// ── PATCH /api/notifications/:id/read ──
// Marks a single notification as read (isRead → true)
router.patch('/:id/read', authenticate, (req: AuthRequest, res: Response) => {
  const notif = notifications.find((n) => n.id === req.params.id);
  if (!notif) {
    res.status(404).json({ error: 'Not found' });
    return;
  }
  notif.isRead = true;
  res.json(notif);
});

export default router;
